# Generated by Django 5.2 on 2025-05-28 23:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BaitType',
            fields=[
                ('bait_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('fresh', models.BooleanField(default=False)),
                ('salt', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='BodyOfWater',
            fields=[
                ('bow_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('lng', models.FloatField()),
                ('lat', models.FloatField()),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='FishType',
            fields=[
                ('fish_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('fresh', models.BooleanField(default=False)),
                ('salt', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='FishingLog',
            fields=[
                ('catch_id', models.AutoField(primary_key=True, serialize=False)),
                ('bait_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DBconnection.baittype')),
                ('bow_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DBconnection.bodyofwater')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('fish_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DBconnection.fishtype')),
            ],
        ),
    ]
